### ISSUE TITLE
fqdn option

### ISSUE THREAD

**Issue by rmoriz** [gregf/chef-apticron#2]
IMHO `default['apticron']['all_fqdns'] = '1'` is not good default, because in this case apticron uses `hostname --all-fqdns` to look up the local hostname(s) which silently discards all hostnames without a proper reverse DNS mapping.

e.g. under kitchen in vagrant this is the case every time.

**Comment by gregf** [comment]
I just chose default values here, I'm happy to accept a patch though.

**Comment by rmoriz** [comment]
yeah, looks like the apticron-thing is rather ugly :(
